# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarbdemo
team: pus
replicas:
  min: 1
  max: 2
  cpuThresholdPercentage: 50
port: 8080
webproxy: true
healthcheck:
  liveness:
    path: veilarbdemo/internal/isAlive
    initialDelay: 20
  readiness:
    path: veilarbdemo/internal/selftest
    initialDelay: 20
prometheus:
  enabled: true
  path: veilarbdemo/internal/metrics
resources:
  limits:
    cpu: 3
fasitResources:
  used:
  - alias: loadbalancer:veilarbdemo
    resourceType: loadbalancerconfig
  - alias: srvveilarbdemo
    resourceType: credential
  - alias: appdynamics
    resourceType: applicationproperties
  exposed:
  - alias: veilarbdemoAPI
    resourceType: restservice
    path: /veilarbdemo/api
alerts:
- alert: Feil i selftest
  expr: selftests_aggregate_result_status{app="veilarbdemo-fss"} > 0
  for: 3m
  labels:
    severity: Warning
  annotations:
    action: Undersøk veilarbdemo/internal/selftest for å se hva som er feil