# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarbdemo
team: pus
replicas:
  min: 1
  max: 2
  cpuThresholdPercentage: 50
port: 8080
webproxy: true
healthcheck:
  liveness:
    path: veilarbdemo/internal/isAlive
    initialDelay: 20
  readiness:
    path: veilarbdemo/internal/isReady
    initialDelay: 20
prometheus:
  enabled: true
  path: veilarbdemo/internal/metrics
resources:
  limits:
    cpu: 3
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
fasitResources:
  used:
  - alias: loadbalancer:veilarbdemo
    resourceType: loadbalancerconfig
  - alias: srvveilarbdemo
    resourceType: credential
  - alias: appdynamics
    resourceType: applicationproperties
  - alias: aad_b2c_discovery # brukes ikke av appen, kun for testing
    resourceType: baseurl
  exposed:
  - alias: veilarbdemoAPI
    resourceType: restservice
    path: /veilarbdemo/api
alertProfiles:
  - common-java-modules
