# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarbdemo
team: pus
replicas:
  min: 1
  max: 2
  cpuThresholdPercentage: 50
port: 8080
webproxy: true
healthcheck:
  liveness:
    path: veilarbdemo/internal/isAlive
    initialDelay: 60
  readiness:
    path: veilarbdemo/internal/selftest
    initialDelay: 60
prometheus:
  enabled: true
  path: veilarbdemo/internal/metrics
fasitResources:
  used:
  - alias: srvveilarbdemo
    resourceType: credential
  - alias: appdynamics
    resourceType: applicationproperties
alerts:
- alert: Feil i selftest
  expr: selftests_aggregate_result_status{app="veilarbdemo"} > 0
  for: 3m
  labels:
    severity: Warning
  annotations:
    action: Undersøk veilarbdemo/internal/selftest for å se hva som er feil