# ref https://raw.githubusercontent.com/nais/naiserator/master/examples/nais-max.yaml
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbdemo
  namespace: {{namespace}}
  labels:
    team: pus
spec:
  image: docker.pkg.github.com/navikt/veilarbdemo/veilarbdemo:{{version}}
  team: pus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  port: 8080
  ingresses:
    - https://veilarbdemo-{{namespace}}.nais.preprod.local
    - https://app-{{namespace}}.adeo.no/veilarbdemo
  webproxy: true
  healthcheck:
    liveness:
      path: veilarbdemo/internal/isAlive
      initialDelay: 20
    readiness:
      path: veilarbdemo/internal/isReady
      initialDelay: 20
  prometheus:
    enabled: true
    path: veilarbdemo/internal/metrics
  resources:
    limits:
      cpu: "3"
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    - APPDYNAMICS_CONTROLLER_HOST_NAME
    - APPDYNAMICS_CONTROLLER_PORT
    - APPDYNAMICS_CONTROLLER_SSL_ENABLED
    - name: FOO
      value: bar