version: 2.1
orbs:
  nais: 'navikt/nais-deployment@1.1.1'
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn verify
      - run:
          name: Sett versjon
          command: echo "export VERSION=$(git rev-list --count HEAD).$(date +'%Y%m%d.%H%M')" >> $BASH_ENV
      - run:
          name: Tagg med versjon $VERSION
          command: echo $VERSION
  deploy:
    docker:
      - image: navikt/pus-iac
    steps:
      - run:
          name: Oppdater pus-iac
          command: echo $VERSION
workflows:
  version: 2
  commit:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only: master
