version: 2.1
description: Orb for produktteam oppfølging

orbs:
  pus: navikt/pus-orb@0.0.1

workflows:
  version: 2
  commit:
    jobs:
      - pus/test-backend:
          context: pus
          filters:
            branches:
              ignore: master
      - pus/deploy-backend:
          context: pus
          filters:
            branches:
              only: master