version: 2.1
orbs:
  nais: 'navikt/nais-deployment@1.1.1'
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn verify
  build-and-push:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - run: mvn package -B -q -DskipTests
      - add_ssh_keys
      - run:
            name: Sett versjon
            command: echo "export VERSION=$(git rev-list --count HEAD).$(date +'%Y%m%d.%H%M')" >> $BASH_ENV
      - run:
          name: Tagg git-repo
          command: |
            git config user.email $GIT_AUTHOR_EMAIL
            git config user.name $GIT_AUTHOR_NAME
            git tag -a $VERSION -m $VERSION HEAD
            git push --tags
      - run:
          name: Bygg docker image
          command: |
            docker build -t navikt/veilarbdemo .
            docker tag navikt/veilarbdemo navikt/veilarbdemo:$VERSION
      - run:
          name: Push docker image
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
            docker push navikt/veilarbdemo
            echo "Pushet versjon $VERSION av veilarbdemo"
            echo "https://cloud.docker.com/u/navikt/repository/docker/navikt/veilarbdemo"ga
  deploy:
    docker:
      - image: navikt/pus-iac:33.20190711.0759
    working_directory: /
    steps:
      - run:
          name: Oppdater pus-iac
          command: node ./update-iac.js $VERSION
workflows:
  version: 2
  commit:
    jobs:
      - test
      - build-and-push:
          context: NAIS deployment
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build-and-push
          filters:
            branches:
              only: master

