version: 2.1
description: Orb for produktteam oppfølging

orbs:
  pus:
    executors:
      pus-iac:
        docker:
          - image: navikt/pus-iac
    jobs:
      test:
        executor: pus-iac
        steps:
          - checkout
          - run:
              name: Last ned settings.xml
              command: |
                curl -o .circleci/settings.xml -L -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3.raw" "api.github.com/repos/navikt/pus-iac/contents/settings.xml"
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "pom.xml" }}
          - run: mvn -B -s .circleci/settings.xml dependency:go-offline
          - save_cache:
              paths:
                - ~/.m2
              key: v1-dependencies-{{ checksum "pom.xml" }}
          - run: mvn -B -s .circleci/settings.xml verify
          - store_test_results:
              path: target/surefire-reports
      build-and-deploy:
        executor: pus-iac
        steps:
          - checkout
          - setup_remote_docker
          - add_ssh_keys
          - run:
              name: Last ned settings.xml
              command: |
                curl -o .circleci/settings.xml -L -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3.raw" "api.github.com/repos/navikt/pus-iac/contents/settings.xml"
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "pom.xml" }}
          - run: mvn -B -s .circleci/settings.xml dependency:go-offline
          - save_cache:
              paths:
                - ~/.m2
              key: v1-dependencies-{{ checksum "pom.xml" }}
          - run: mvn -B -s .circleci/settings.xml package -B -q
          - store_test_results:
              path: target/surefire-reports
          - run:
              name: Sett versjon
              command: echo "export VERSION=$(git rev-list --count HEAD).$(date +'%Y%m%d.%H%M')" >> $BASH_ENV
          - run:
              name: Tag git repo
              command: |
                git config user.email $GIT_AUTHOR_EMAIL
                git config user.name $GIT_AUTHOR_NAME
                git tag -a $VERSION -m $VERSION HEAD
                git push --tags
          - run:
              name: Bygg docker image
              command: |
                docker build -t navikt/$CIRCLE_PROJECT_REPONAME .
                docker tag navikt/$CIRCLE_PROJECT_REPONAME navikt/$CIRCLE_PROJECT_REPONAME:$VERSION
          - run:
              name: Push docker image
              command: |
                echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
                docker push navikt/$CIRCLE_PROJECT_REPONAME
                echo "Pushet versjon $VERSION av $CIRCLE_PROJECT_REPONAME"
                echo "https://cloud.docker.com/u/navikt/repository/docker/navikt/$CIRCLE_PROJECT_REPONAME"
          - run:
              name: Oppdater pus-iac
              command: echo $VERSION

workflows:
  version: 2
  commit:
    jobs:
      - pus/test:
          context: pus
          filters:
            branches:
              ignore: master
      - pus/build-and-deploy:
          context: pus
          filters:
            branches:
              only: master