version: 2.1
orbs:
  nais: 'navikt/nais-deployment@1.1.1'
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn verify
  build:
    machine: true
    steps:
      - checkout
      - add_ssh_keys
      - run:
            name: Sett versjon
            command: echo "export VERSION=$(git rev-list --count HEAD).$(date +'%Y%m%d.%H%M')" >> $BASH_ENV
      - run:
          name: Tagg git-repo med versjon $VERSION
          command: |
            git config user.email $GIT_AUTHOR_EMAIL
            git config user.name $GIT_AUTHOR_NAME
            git tag -a $VERSION -m $VERSION HEAD
            git push --tags
      - run:
          name: Bygg og push docker image for versjon $VERSION
          command: |
            docker build -t navikt/veilarbdemo .
            docker tag navikt/veilarbdemo navikt/veilarbdemo:$VERSION
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
            docker push navikt/veilarbdemo
            echo "Pushet versjon $VERSION av veilarbdemo"
            echo "https://cloud.docker.com/u/navikt/repository/docker/navikt/veilarbdemo"

  deploy:
    docker:
      - image: navikt/pus-iac
    steps:
      - run:
          name: Oppdater pus-iac
          command: node src/update-iac.js $VERSION
workflows:
  version: 2
  commit:
    jobs:
      - test
      - build:
          context: NAIS deployment
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

