version: 2.1
orbs:
  pus: navikt/pus-orb@0.0.16

workflows:
  version: 2
  commit:
    jobs:
      - pus/test-backend:
          context: pus
          filters:
            branches:
              ignore: master
      - pus/deploy-backend:
          cluster: dev-fss
          filepath: ./nais-q-fss.yaml
          context: pus
          filters:
            branches:
              only: master
      - pus/deploy-latest:
          context: pus
          requires:
            - pus/deploy-backend
          cluster: dev-sbs
          filepath: ./nais-q-sbs.yaml
          filters:
            branches:
              only: master
